name: "books-api"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: profmcdan/books-api
  #   command: php artisan serve --host=0.0.0.0 --port=29000
  #   volumes:
  #     - ./app:/app
  #   ports:
  #     - "29000:29000"
  #   env_file:
  #     - ./.env
  #   restart: always
  #   depends_on:
  #     - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Strong!Pass
      MYSQL_DATABASE: books_db
    ports:
      - "23306:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    ports:
      - "26379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - ./.env

volumes:
  db-data:
  redis-data:

