name: "books-api"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: books-api
    container_name: books-api
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    env_file:
      - ./.env
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Strong!Pass
      MYSQL_DATABASE: books_db
    ports:
      - "23306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    ports:
      - "26379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - ./.env

volumes:
  db-data:
  redis-data:

networks:
  app-network:
    driver: bridge
